services:
    _defaults:
        autowire: true
        autoconfigure: true 

    PBaszak\ExtendedApiDocBundle\:
        resource: '%kernel.project_dir%/vendor/PBaszak/extended-api-doc-bundle/src/'
        exclude:
            - '%kernel.project_dir%/vendor/PBaszak/extended-api-doc-bundle/src/DependencyInjection/'
            - '%kernel.project_dir%/vendor/PBaszak/extended-api-doc-bundle/src/Entity/'
