services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\ExtendedApiDoc\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,ExtendedApiDocBundle.php}'

    ### Documentation generator ###
    Nelmio\ApiDocBundle\Render\RenderOpenApi:
        alias: nelmio_api_doc.render_docs
    nelmio_api_doc.controller.swagger_ui_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Controller\ControllerDecorator
        tags:
            - controller.service_arguments
        arguments:
            - '@nelmio_api_doc.controller.swagger_ui'
    nelmio_api_doc.controller.swagger_json_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Controller\ControllerDecorator
        tags:
            - controller.service_arguments
        arguments:
            - '@nelmio_api_doc.controller.swagger_json'
    nelmio_api_doc.controller.swagger_yaml_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Controller\ControllerDecorator
        tags:
            - controller.service_arguments
        arguments:
            - '@nelmio_api_doc.controller.swagger_yaml'
    
    # Documentation
    nelmio_api_doc.render_docs.yaml:
        class: Nelmio\ApiDocBundle\Render\Yaml\YamlOpenApiRenderer
    nelmio_api_doc.render_docs.json:
        class: Nelmio\ApiDocBundle\Render\Json\JsonOpenApiRenderer
    nelmio_api_doc.render_docs.html:
        class: Nelmio\ApiDocBundle\Render\Html\HtmlOpenApiRenderer
        arguments:
            - '@twig'
    documentation_nelmio_api_doc.render_docs.html:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\HtmlOpenApiRendererDecorator
        decorates: nelmio_api_doc.render_docs.html
        decoration_priority: 10
        arguments:
            $decorated: '@documentation_nelmio_api_doc.render_docs.html.inner'
            $twig: '@twig'
    documentation.html_sort_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererSortDecorator
        decorates: nelmio_api_doc.render_docs.html
        arguments:
            $decorated: '@documentation.html_sort_decorator.inner'
    documentation.json_sort_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererSortDecorator
        decorates: nelmio_api_doc.render_docs.json
        arguments:
            $decorated: '@documentation.json_sort_decorator.inner'
    documentation.yaml_sort_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererSortDecorator
        decorates: nelmio_api_doc.render_docs.yaml
        arguments:
            $decorated: '@documentation.yaml_sort_decorator.inner'
    documentation.html_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererDecorator
        decorates: nelmio_api_doc.render_docs.html
        decoration_priority: 1
        arguments:
            $decorated: '@documentation.html_decorator.inner'
            $router: '@router'
    documentation.json_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererDecorator
        decorates: nelmio_api_doc.render_docs.json
        decoration_priority: 1
        arguments:
            $decorated: '@documentation.json_decorator.inner'
            $router: '@router'
    documentation.yaml_decorator:
        class: PBaszak\ExtendedApiDoc\Nelmio\ApiDocBundle\Render\OpenApiRendererDecorator
        decorates: nelmio_api_doc.render_docs.yaml
        decoration_priority: 1
        arguments:
            $decorated: '@documentation.yaml_decorator.inner'
            $router: '@router'
    ### /Documentation generator ###

twig:
    paths:
        - '%kernel.project_dir%/vendor/pbaszak/extended-api-doc-bundle/src/Resources/views'
